jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build Everything
      - run:
          command: yarn test -- --coverage
          name: Run Tests with Coverage
      - run:
          command: bash <(curl -s https://codecov.io/bash)
          name: Upload Coverage
orbs:
  node: 'circleci/node@3.0.0'
version: 2.1
workflows:
  test_my_app:
    jobs:
      - build-and-test
