version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm install -g yarn
      - run:
          command: yarn install
      - run:
          command: yarn build
      - run:
          command: yarn test -- --coverage
      - run:
          command: bash <(curl -s https://codecov.io/bash)
workflows:
    build-and-test:
      jobs:
        - build-and-test
